Repository TEAM-LifeTail/2024-sharedog-frontend, pull requests merged in 2025-01, with the labels that each got.

#36 ✨ [Feature] #35 - 테스트페이지 구현중 중간저장
  src/components/main/TestSlide.jsx
  src/hooks/useShouldHideFooter.js
  src/layout/TestLayout.jsx
  src/pages/mainPage/MainPage.jsx
  src/pages/testPage/TestPage.jsx
  src/pages/testPage/TestPage.styled.js
  src/pages/testPage/TestStartPage.jsx
  src/pages/testPage/TestStartPage.styled.js
  src/router.jsx
  src/styles/theme.js
Labels: ✨ Feature, 🛠️ Fix, 🐾 동건

#38 [Feature] #37 - 커뮤니티 페이지 UI 구현중 중간저장
  src/assets/icons/Filter.svg
  src/assets/icons/Search.svg
  src/pages/communityPage/Community.jsx
  src/pages/communityPage/CommunityPage.styled.js
Labels: 🎨 Design, 🐾 효은

#39 ✨ [Feature] #35 - 헌혈견테스트 결과페이지제외 구현완료
  src/assets/images/testStartLogo.png
  src/assets/images/vetDoctorCut.png
  src/components/main/TestSlide.jsx
  src/components/test/TestHeader.jsx
  src/components/test/TestLoading.jsx
  src/components/test/TestQna.jsx
  src/components/test/TestQna.styled.js
  src/components/test/TestStartPgBtn.jsx
  src/data/testData/TestData.js
  src/hooks/useCustomNavigate.js
  src/layout/TestLayout.jsx
  src/pages/loginPage/WelcomePage.jsx
  src/pages/testPage/TestPage.jsx
  src/pages/testPage/TestPage.styled.js
  src/pages/testPage/TestResultNoPage.jsx
  src/pages/testPage/TestResultOkPage.jsx
  src/pages/testPage/TestResultPage.styled.js
  src/pages/testPage/TestStartPage.jsx
  src/pages/testPage/TestStartPage.styled.js
  src/router.jsx
  src/styles/theme.js
Labels: 🎨 Design, ✨ Feature, 🐾 동건

#42 ✨ [Feature] #35 - 테스트 결과화면 구현!
  package-lock.json
  src/assets/icons/resultBlood.png
  src/assets/images/testok.png
  src/components/test/TestStartPgBtn.jsx
  src/pages/testPage/TestResultNoPage.jsx
  src/pages/testPage/TestResultOkPage.jsx
  src/pages/testPage/TestResultPage.styled.js
  src/pages/testPage/TestStartPage.jsx
Labels: 🎨 Design, ✨ Feature, 🐾 동건

#44 ✨ [Feature] #35 -테스트페이지 전용 OG설정
  public/test.html
  public/testThumbnail.png
  vercel.json
  vite.config.js
Labels: ✨ Feature, 🐾 동건

#46 [Feature] 커뮤니티 페이지 UI 구현 및 더미데이터 연결 #19
  src/assets/icons/comment.svg
  src/assets/icons/good.svg
  src/components/post/BloodPostCard.jsx
  src/components/post/BloodPostCard.styled.js
  src/data/mainData/Posts.js
  src/hooks/useShouldHideFooter.js
  src/pages/communityPage/Community.jsx
  src/pages/communityPage/CommunityPage.styled.js
  src/pages/loginPage/LoginPage.jsx
  src/pages/loginPage/LoginPage.styled.js
Labels: 🎨 Design, ✨ Feature, 🐾 효은

#48 ✨ [Feature] #35 -카카오 공유하기기능 임시적용
  index.html
  public/test.html
  src/hooks/useKaKaoShare.js
  src/hooks/useShouldHideFooter.js
  src/pages/testPage/TestStartPage.jsx
Labels: ✨ Feature, 🐾 동건

#50 🐛 [Fix] #35 -라우터 경로오류수정
  src/router.jsx
Labels: 🛠️ Fix, 🐾 동건

#52 ✨ [Feature] #35 - 테스트 카카오 공유하기 연결완료
  src/hooks/useKaKaoShare.js
  src/pages/testPage/TestResultNoPage.jsx
  src/pages/testPage/TestResultOkPage.jsx
  src/pages/testPage/TestStartPage.jsx
Labels: ✨ Feature, 🐾 동건

#56 🐛 [Fix] #55 - 카카오 공유하기 인앱브라우저문제 수정
  public/test.html
  vercel.json
Labels: 🛠️ Fix, 🐾 동건

#61 ✨ [Feature] #55 - 카카오 로그인 구현완료
  index.html
  jsconfig.json
  package-lock.json
  package.json
  public/test.html
  src/App.jsx
  src/apis/axiosInstance.js
  src/hooks/useKakaoAuth.jsx
  src/pages/loginPage/KakaoCallbackPage.jsx
  src/pages/loginPage/WelcomePage.jsx
  src/router.jsx
  vite.config.js
Labels: 🔗API, ✨ Feature, 🐾 동건

#63 ✨ [Feature] #55 - 카카오 로그아웃구현 &&마이페이지 api연결..
  src/apis/axiosInstance.js
  src/apis/refreshTokenUtil.js
  src/pages/myPage/AccountManagement.jsx
Labels: 🔗API, ✨ Feature, 🐾 동건

#67 🐛 [Feature] #21 - 안보냈던 pr 다시보냄
  index.html
  public/favicon.ico
Labels: 🛠️ Fix, 🐾 동건
