Repository TEAM-LifeTail/2024-sharedog-frontend, pull requests merged in 2025-04, with the labels that each got.

#173 🐛 [Fix] #136 - 채팅리스트 웹소켓 수정
  src/pages/chatPage/ChatPage.jsx
Labels: 🛠️ Fix, 🐾 동건

#175 🐛 [Fix] #136 - 채팅 웹소켓 구현완료 마이페이지 푸터수정
  src/components/chat/ChatRoom.jsx
  src/pages/chatPage/ChatDetailPage.jsx
  src/pages/chatPage/ChatPage.jsx
  src/pages/myPage/LegalDocument.styled.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#176 🐛 [Fix] #136 - 깃 병합 꼬인거 다시 수정 커뮤니티 하트 svg변경
  src/components/community/CommunityPost.jsx
  src/pages/chatPage/ChatPage.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#178 🐛 [Fix] #136 - 약속잡기 채팅리스트 오류 수정
  src/components/community/CommunityPost.jsx
  src/components/main/Post.jsx
  src/pages/chatPage/ChatPage.jsx
  src/pages/mainPage/MainPage.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#182 🐛 [Fix] #136 - 채팅 리스트 시간순정렬수정 등등
  src/components/main/CountSlide.jsx
  src/components/mypage/ReservationCard.jsx
  src/components/mypage/ReservationCard.styled.js
  src/layout/DefaultLayout.jsx
  src/pages/chatPage/ChatPage.jsx
  src/pages/myPage/PetInfo.jsx
  src/styles/global.js
  src/styles/theme.js
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#188 🐛 [Fix] #136 - 카카오로그인 토큰 관리 수정
  src/pages/mainPage/MainPage.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#187 🔥[Remove] / #143 console.log 주석 처리
  src/components/community/Comment.jsx
  src/pages/communityPage/CommunityDetail.jsx
  src/pages/communityPage/CommunitySearch.jsx
  src/pages/communityPage/CommunityWrite.jsx
Labels: 🐾 수용

#190 🐛 [Fix] #136 - 쿠키허용 삭제
  src/apis/axiosInstance.js
  src/router.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#192 🐛 [Fix] #136 - 헌혈예약내역페이지 api수정
  src/apis/axiosInstance.js
  src/pages/myPage/Reservation.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#194 🐛 [Fix] #136 - KakaoAuthProvider에서 localStorage의 토큰을 동기식 초기값으로 설정
  src/hooks/useKakaoAuth.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#198 🐛 [Fix] #136 - 채팅수정, 커뮤니티 글쓰기 확대방지
  src/pages/chatPage/ChatDetailPage.jsx
  src/pages/communityPage/CommunityWrite.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#200 🐛 [Fix] #136 - 채팅리스트,채팅,커뮤니티 QA수정
  src/components/chat/ChatRoom.jsx
  src/pages/chatPage/ChatDetailPage.jsx
  src/pages/communityPage/CommunityNew.jsx
Labels: 🔗API, 🎨 Design, 🛠️ Fix, 🐾 동건

#202 💄 [Design] #136 - 메인페이지 post 혈액형 태그 수정
  src/pages/mainPage/MainPage.jsx
Labels: 🎨 Design, 🐾 동건

#209 🐛 [Fix] / #204 : 커뮤니티 사진 규격 수정 및 최근 검색어 오류 해결
  src/pages/communityPage/CommunityDetail.styled.js
  src/pages/communityPage/CommunityNew.jsx
  src/pages/communityPage/CommunitySearch.jsx
Labels: 🛠️ Fix, 🐾 수용

#210 💄 [Design] #136 - 커뮤니티 디테일페이지 혈액형 태그수정
  src/pages/communityPage/CommunityDetail.jsx
Labels: 🎨 Design, 🛠️ Fix, 🐾 동건

#212 🐛 [Fix] / #204 : 검색어 삭제 기능 오류 해결
  src/pages/communityPage/CommunitySearch.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 수용

#213 ✨ [Feat] / #204 : 전체삭제 api 연결 완료
  src/pages/communityPage/CommunitySearch.jsx
Labels: 🔗API, ✨ Feature, 🐾 수용
