Repository TEAM-LifeTail/2024-sharedog-frontend, pull requests merged in 2025-02, with the labels that each got.

#74 [✨Feature] #71 회원가입, 로그인 페이지 API 구현 완료
  src/components/signup/SignUpForm.jsx
  src/pages/loginPage/LoginPage.jsx
  src/pages/signUpPage/NameSignUpPage.jsx
  src/pages/signUpPage/PhoneSignUpPage.jsx
  src/pages/signUpPage/PwSignUpPage.jsx
  src/pages/signUpPage/SignUpPage.jsx
  src/pages/signUpPage/SignupFormContainer.jsx
  src/router.jsx
Labels: 🔗API, ✨ Feature, 🛠️ Fix, 🐾 수용

#73 [Design] #58 마이페이지 UI 다듬기
  src/pages/myPage/PetAdd.jsx
  src/pages/myPage/PetAdd.styled.js
  src/pages/myPage/PetEdit.jsx
  src/pages/myPage/PetInfo.jsx
  src/pages/myPage/PetInfo.styled.js
  src/pages/myPage/Reservation.jsx
  src/pages/myPage/Reservation.styled.js
Labels: 🎨 Design

#75 [Design] #66 커뮤니티페이지 글 반응형 수정
  src/components/post/BloodPostCard.styled.js
  src/pages/communityPage/CommunityPage.styled.js
Labels: 🎨 Design, 🐾 효은

#77 🐛 [Fix] #76 -일반로그인 API에러 수정완
  src/hooks/useKakaoAuth.jsx
  src/pages/loginPage/LoginPage.jsx
  src/pages/loginPage/LoginPage.styled.js
  src/pages/loginPage/WelcomePage.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#79 🔧 [Chore] #76 - 로컬 개발 환경 HTTPS 적용
  .gitignore
  package-lock.json
  package.json
  vite.config.js
Labels: 🔗API, 🐾 동건

#82 💄 [Design] #81 - 홈화면QA+이름부분 API연결
  src/components/main/NavBtn.jsx
  src/components/main/Post.jsx
  src/components/main/TestSlide.jsx
  src/data/mainData/Posts.js
  src/pages/mainPage/MainPage.jsx
  src/pages/mainPage/MainPage.styled.js
Labels: 🔗API, 🎨 Design, 🐾 동건

#84 ✨ [Feature] #81 - 비로그인시 모달,블락박스구현 테스트수정
  .gitignore
  src/components/main/LoginRequiredBox.jsx
  src/components/main/LoginRequiredModal.jsx
  src/hooks/useShare.js
  src/pages/mainPage/MainPage.jsx
  src/pages/testPage/TestResultNoPage.jsx
  src/pages/testPage/TestResultOkPage.jsx
  src/pages/testPage/TestStartPage.jsx
  src/styles/theme.js
Labels: ✨ Feature, 🛠️ Fix, 🐾 동건

#86 🐛 [Fix] #81 - 로그인 api연결오류수정
  src/apis/axiosInstance.js
  src/apis/refreshTokenUtil.js
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#87 💄 [Design] 홈화면 모달,블락박스 수정
  src/components/main/LoginRequiredBox.jsx
  src/components/main/LoginRequiredModal.jsx
  src/pages/mainPage/MainPage.jsx
Labels: 🎨 Design, 🐾 동건

#88 ✨ [Feature] #81 - 홈화면 필터,게시글 api연결,모달x버튼위치수정
  src/components/main/LoginRequiredModal.jsx
  src/pages/loginPage/WelcomePage.styled.js
  src/pages/mainPage/MainPage.jsx
  src/pages/mainPage/MainPage.styled.js
Labels: 🔗API, 🎨 Design, ✨ Feature, 🐾 동건

#89 💄 [Design] #81 슬라이드2번 디자인수정 테스트디자인QA수정
  src/components/main/PetSlide.jsx
  src/components/main/Post.jsx
  src/components/test/TestQna.styled.js
  src/pages/mainPage/MainPage.jsx
  src/pages/testPage/TestResultNoPage.jsx
Labels: 🎨 Design, 🐾 동건

#90 ♻️ [Reafactor] #76 - 마이페이지 api연결, 디자인 안맞는거 수정
  src/assets/icons/myBackIcon.svg
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.styled.js
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#91 ✨ [Feature] #81 - 테스트했을때 슬라이드 위치변경
  src/components/main/MainSlider.jsx
  src/pages/mainPage/MainPage.jsx
  src/pages/testPage/TestResultNoPage.jsx
  src/pages/testPage/TestResultOkPage.jsx
Labels: 🔗API, ✨ Feature, 🐾 동건

#94 ✨ [Feature] #37 - 커뮤니티메인 구현중간저장
  src/assets/icons/QnaIcon.png
  src/assets/icons/Search.svg
  src/assets/icons/backIconNew.svg
  src/assets/icons/bloodIcon.png
  src/assets/icons/filterIcon.svg
  src/assets/icons/goodIcon.png
  src/assets/icons/talkIcon.png
  src/components/community/CommunityPost.jsx
  src/pages/communityPage/CommunityNew.jsx
  src/pages/communityPage/CommunityNew.styled.js
  src/pages/communityPage/CommunitySearch.jsx
  src/pages/myPage/AccountManagement.jsx
  src/pages/myPage/MyPage.jsx
  src/router.jsx
  src/styles/theme.js
Labels: 🎨 Design, ✨ Feature, 🐾 동건

#98 ✨ [Feature] #37 - 커뮤니티메인 구현완료 api연결완료
  src/components/community/DropDown.jsx
  src/pages/communityPage/CommunityNew.jsx
  src/pages/communityPage/CommunityNew.styled.js
Labels: 🔗API, 🎨 Design, ✨ Feature, 🐾 동건

#101 💄 [Design] #54 -채팅헤더 상단고정
  src/pages/chatPage/ChatDetail.styled.js
Labels: 🎨 Design, 🐾 동건

#104 💄 [Design] #103 - 플로팅버튼+푸터10px높임
  src/assets/icons/writeIcon.svg
  src/components/common/CommonFooter.styled.js
  src/pages/communityPage/Community.jsx
  src/pages/communityPage/CommunityNew.jsx
  src/pages/communityPage/CommunityNew.styled.js
  src/pages/communityPage/CommunityPage.styled.js
Labels: 🎨 Design, ✨ Feature, 🐾 동건

#106 ✨ [Feature] #54 -웹소켓 채팅 작동은됨 오류있음
  src/components/chat/ChatFooter.jsx
  src/pages/chatPage/ChatDetail.styled.js
  src/pages/chatPage/ChatDetailPage.jsx
Labels: 🔗API, ✨ Feature, 🐾 동건
