Repository TEAM-LifeTail/2024-sharedog-frontend, pull requests merged in 2025-03, with the labels that each got.

#108 🐛 [Fix] #54 - 채팅완벽구현완
  src/components/chat/ChatFooter.jsx
  src/pages/chatPage/ChatDetailPage.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#110 ✨ [Feature] /#71 커뮤니티 게시물 글쓰기 post API 연결 완료 및 취소 버튼 경로 수정
  src/pages/communityPage/CommunityWrite.jsx
  src/pages/communityPage/CommunityWrite.styled.js
Labels: 🔗API, ✨ Feature, 🐾 수용

#111 ✨ [Feature] /#71 상세글 페이지 API 연결 및 UI 디자인 완료
  src/assets/icons/Delete.svg
  src/hooks/useShouldHideFooter.js
  src/pages/communityPage/CommunityDetail.jsx
  src/pages/communityPage/CommunityDetail.styled.js
  src/pages/communityPage/CommunityWrite.jsx
  src/router.jsx
Labels: 🔗API, 🎨 Design, ✨ Feature, 🛠️ Fix, 🐾 수용

#112 ✨ [Feature] /#71 상세글 삭제 api 연결 완료
  src/pages/communityPage/CommunityDetail.jsx
  src/pages/communityPage/CommunityDetail.styled.js
Labels: 🔗API, ✨ Feature, 🐾 수용

#114 ♻️ [Refactor] #76 - 마이페이지, 계정정보페이지 수정
  src/assets/icons/myPage/MyPageAccount.svg
  src/assets/icons/myPage/MyPageInquiry.svg
  src/assets/icons/myPage/MyPageNote.svg
  src/assets/icons/myPage/MypageHeart.svg
  src/assets/icons/myPage/MypageWrite.svg
  src/assets/icons/myPage/dogAccount.svg
  src/assets/icons/profileEditIcon.svg
  src/components/mypage/MyNextBtn.jsx
  src/pages/loginPage/LoginPage.jsx
  src/pages/myPage/AccountManagement.jsx
  src/pages/myPage/AccountManagement.styled.js
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.styled.js
  src/styles/theme.js
Labels: 🎨 Design, 🐾 동건

#115 ✨ [Feature]/#113 최근 검색어 api, ui 구현 완료
  src/pages/communityPage/CommunitySearch.jsx
  src/pages/communityPage/CommunitySearch.styled.js
Labels: 🔗API, 🎨 Design, ✨ Feature, 🐾 수용

#117 ✨ [Feature] #54 - 채팅약속잡기구현 OG수정&로그인페이지수정
  index.html
  public/thumbnail.png
  public/thumbnail2.png
  src/pages/chatPage/ChatDetail.styled.js
  src/pages/chatPage/ChatDetailPage.jsx
  src/pages/loginPage/LoginPage.jsx
  src/pages/loginPage/LoginPage.styled.js
Labels: 🔗API, 🎨 Design, ✨ Feature, 🛠️ Fix, 🐾 동건

#119 [✨Feature]/#113 댓글 api 연결 및 ui 구현 완료
  src/assets/icons/ComCir.svg
  src/assets/icons/Send.svg
  src/components/community/Comment.jsx
  src/pages/communityPage/CommunityDetail.jsx
  src/pages/communityPage/CommunityDetail.styled.js
Labels: 🔗API, 🎨 Design, ✨ Feature, 🐾 수용

#120 🐛 [Fix]/#113 댓글 옆에 프로필 이미지 안뜨는 오류 수정
  src/pages/communityPage/CommunityDetail.styled.js
Labels: 🛠️ Fix, 🐾 수용

#121 [✨Feature]/#113 좋아요 및 좋아요 취소 기능 구현 완료
  src/assets/icons/Wlike.svg
  src/pages/communityPage/CommunityDetail.jsx
  src/pages/communityPage/CommunityDetail.styled.js
  src/pages/communityPage/CommunitySearch.jsx
Labels: 🔗API, ✨ Feature, 🐾 수용

#123 ✨ [Feature] #54 - 엔터키로로그인 채팅읽음 약속잡기구현
  src/assets/icons/promiseIcon.svg
  src/components/chat/MyChat.jsx
  src/components/chat/PeerChat.jsx
  src/components/chat/PromiseCard.jsx
  src/pages/chatPage/ChatDetail.styled.js
  src/pages/chatPage/ChatDetailPage.jsx
  src/pages/loginPage/LoginPage.jsx
Labels: 🔗API, 🎨 Design, ✨ Feature, 🐾 동건

#125 [✨Feature]/#113 내가 쓴 댓글에는 채팅하기 버튼 없도록 구현
  src/components/community/Comment.jsx
  src/pages/communityPage/CommunityDetail.jsx
Labels: ✨ Feature, 🛠️ Fix, 🐾 수용

#126 💄 [Design] #54 - 약속잡기 디자인 완벽수정 datepicker라이브러리사용
  package-lock.json
  package.json
  src/assets/icons/promiseSelect.svg
  src/components/chat/DateInput.jsx
  src/components/chat/TimeInput.jsx
  src/pages/chatPage/ChatDetail.styled.js
  src/pages/chatPage/ChatDetailPage.jsx
  src/pages/communityPage/CommunityDetail.jsx
Labels: 🎨 Design, 🐾 동건

#128 ✨ [Feature] #76 -마이페이지 강아지 추가 수정 완료
  src/components/mypage/PetCard.jsx
  src/pages/myPage/LegalDocument.styled.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.styled.js
  src/pages/myPage/PetAdd.jsx
  src/pages/myPage/PetAdd.styled.js
  src/pages/myPage/PetEdit.jsx
  src/pages/myPage/PetEdit.styled.js
  src/pages/myPage/PetInfo.jsx
  src/pages/myPage/PetInfo.styled.js
  src/pages/myPage/PrivacyPolicyPage.jsx
  src/pages/myPage/TermsPage.jsx
  src/router.jsx
Labels: 🔗API, 🎨 Design, ✨ Feature, 🐾 동건

#130 ✨ [Feature] #76 - 헌혈약속 내역 구현완
  src/components/chat/PromiseCard.jsx
  src/components/main/MainSlider.jsx
  src/components/main/PetSlide.jsx
  src/components/mypage/ReservationCard.jsx
  src/components/mypage/ReservationCard.styled.js
  src/pages/mainPage/MainPage.jsx
  src/pages/mainPage/MainPage.styled.js
  src/pages/myPage/Reservation.jsx
Labels: 🔗API, 🎨 Design, ✨ Feature, 🐾 동건

#132 [✨Feature]/#113 이미지 2장 이상인 경우 한장씩만 보이고 스크롤 되도록 설정, 댓글 옆 이미지 찌그러짐 수정
  src/components/community/Comment.jsx
  src/pages/communityPage/CommunityDetail.styled.js
Labels: ✨ Feature, 🛠️ Fix, 🐾 수용

#133 ♻️ [Refactor] #54 - 댓글채팅방만들기 props추가
  src/components/community/Comment.jsx
  src/pages/communityPage/CommunityDetail.jsx
Labels: 🔗API, ✨ Feature, 🐾 동건

#134 ✨ [Feature] #76 - 마이페이지 약관페이지 2개 개발 완
  src/hooks/useShouldHideFooter.js
  src/pages/myPage/LegalDocument.styled.jsx
  src/pages/myPage/PrivacyPolicyPage.jsx
  src/pages/myPage/TermsPage.jsx
Labels: 🎨 Design, ✨ Feature, 🐾 동건

#137 [✨Feature]/#113 댓글 Enter 눌러도 등록되도록 설정
  src/pages/communityPage/CommunityDetail.jsx
Labels: ✨ Feature, 🐾 수용

#139 🐛 [Fix] #136 - 글씨쓸때 확대되는거 방지용 훅 개발
  src/hooks/usePreventZoom.js
  src/pages/chatPage/ChatDetailPage.jsx
  src/pages/communityPage/CommunityDetail.jsx
  src/pages/communityPage/CommunityNew.jsx
  src/pages/loginPage/LoginPage.jsx
Labels: 🎨 Design, 🛠️ Fix, 🐾 동건

#141 [✨Feature]/#138 내가 쓴 글 불러오기 기능 구현 완료
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyWrite.jsx
  src/pages/myPage/MyWrite.styled.js
  src/router.jsx
Labels: 🔗API, 🎨 Design, ✨ Feature, 🐾 수용

#144 🐛 [Fix]/#143 QA 1차 수정 완료
  src/pages/communityPage/CommunityDetail.jsx
  src/pages/communityPage/CommunityDetail.styled.js
  src/pages/communityPage/CommunitySearch.styled.js
  src/pages/communityPage/CommunityWrite.jsx
  src/pages/myPage/MyWrite.styled.js
Labels: 🎨 Design, ✨ Feature, 🛠️ Fix, 🐾 수용

#145 🐛 [Fix] #136 - 로그인안됐을때 푸터 클릭안되게수정 1ㄷ1문의 연결오류
  src/components/common/CommonFooter.jsx
  src/components/common/CommonFooter.styled.js
  src/components/community/CommunityPost.jsx
  src/pages/myPage/MyPage.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#151 🐛 [Fix] #136 - 각종 수정사항 수정 0323 1차수정
  package-lock.json
  package.json
  src/assets/images/defaultDogImg.png
  src/assets/images/nav1Img.png
  src/assets/images/nav2Img.png
  src/assets/images/nav3Img.png
  src/components/chat/ChatRoom.jsx
  src/components/chat/PromiseCard.jsx
  src/components/common/CommonFooter.jsx
  src/components/main/LoginRequiredModal.jsx
  src/components/main/MainSlider.jsx
  src/components/main/NavBtn.jsx
  src/components/main/PetSlide.jsx
  src/components/mypage/PetCard.jsx
  src/components/mypage/ReservationCard.jsx
  src/hooks/useShouldHideFooter.js
  src/pages/communityPage/CommunityNew.jsx
  src/pages/communityPage/CommunityNew.styled.js
  src/pages/loginPage/WelcomePage.jsx
  src/pages/mainPage/BloodBenefit.jsx
  src/pages/mainPage/BloodCaution.jsx
  src/pages/mainPage/BloodRule.jsx
  src/pages/mainPage/MainPage.jsx
  src/pages/mainPage/MainPage.styled.js
  src/pages/myPage/AccountManagement.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/PetAdd.jsx
  src/pages/myPage/PetEdit.jsx
  src/pages/myPage/PetInfo.jsx
  src/router.jsx
  vite.config.js
Labels: 🔗API, 🎨 Design, 🛠️ Fix, 🐾 동건

#152 ✨ [Feature] #136 - 배포캐시 문제 새로고침하는 코드 추가
  src/main.jsx
Labels: ✨ Feature, 🐾 동건

#154 💄 Design#136 -
  src/components/mypage/PetCard.jsx
  src/components/mypage/PetCard.styled.js
  src/pages/myPage/PetAdd.jsx
  src/pages/myPage/PetEdit.jsx
  src/pages/myPage/PetEdit.styled.js
Labels: 🎨 Design, 🛠️ Fix, 🐾 동건

#160 🐛 [Fix] #136 - 마이페이지 get api오류 디버깅용 알럿추가
  src/pages/myPage/MyPage.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#169 🐛 [Fix] #136 - 마이페이지 api새로연결 채팅리스트 안읽은채팅표시
  src/components/chat/ChatRoom.jsx
  src/pages/chatPage/ChatPage.jsx
  src/pages/myPage/AccountManagement.jsx
  src/pages/myPage/MyPage.jsx
Labels: 🔗API, 🛠️ Fix, 🐾 동건

#171 🐛 [Fix] #136 - 마이페이지 svg경로 대소문자수정
  src/assets/icons/myPage/MypageHeart2.svg
  src/pages/myPage/MyPage.jsx
Labels: 🛠️ Fix, 🐾 동건
